# docker build -t vapour:v1 .
# docker run -it vapour:v1
# kubectl create deployment vapour --image=vapour:v1 #scalatest bash 

FROM broadinstitute/scala-baseimage
COPY $PWD /home/apps/
WORKDIR /home/apps
CMD scala Vapour.scala