
# docker build -t nicearray:v1 .
# docker run -it nicearray:v1
# kubectl create deployment nicearray --image=nicearray:v1 

FROM broadinstitute/scala-baseimage
COPY $PWD /home/apps/
WORKDIR /home/apps
CMD scala Nicearray.scala